# Use official Python image
FROM python:3.9-slim

# Set working directory inside container
WORKDIR /app

# Copy and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app code
COPY . .

# Cloud Run expects the app to listen on port 8080
ENV PORT 8080

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["python", "main.py"]
